//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineProgram.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public int Admin_code { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string AdminLogin { get; set; }
        public string AdminPassword { get; set; }
    }
}
