//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineProgram.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airplanes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Airplanes()
        {
            this.Flights = new HashSet<Flights>();
        }
    
        public int Airplane_code { get; set; }
        public string Airplane_name { get; set; }
        public Nullable<double> Flight_altitude { get; set; }
        public Nullable<double> Flight_speed { get; set; }
        public Nullable<int> Number_of_seats { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flights> Flights { get; set; }
    }
}
