//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirlineProgram.ModelDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbAirlineEntities : DbContext
    {

        private static DbAirlineEntities _context;
        public DbAirlineEntities()
            : base("name=DbAirlineEntities")
        {
        }

        public static DbAirlineEntities GetContext()
        {
            if (_context is null) _context = new DbAirlineEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Airlines> Airlines { get; set; }
        public virtual DbSet<Airplanes> Airplanes { get; set; }
        public virtual DbSet<Airports> Airports { get; set; }
        public virtual DbSet<Citys> Citys { get; set; }
        public virtual DbSet<Flights> Flights { get; set; }
        public virtual DbSet<Passengers> Passengers { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<Сountrys> Сountrys { get; set; }
    }
}
